/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserYourListRouteImport } from './routes/user/your-list'
import { Route as UserHomeRouteImport } from './routes/user/home'
import { Route as UserBoardRouteImport } from './routes/user/board'
import { Route as UserAddJobRouteImport } from './routes/user/add-job'
import { Route as UserEditJobUuidRouteImport } from './routes/user/edit-job.$uuid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserYourListRoute = UserYourListRouteImport.update({
  id: '/your-list',
  path: '/your-list',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserHomeRoute = UserHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserBoardRoute = UserBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAddJobRoute = UserAddJobRouteImport.update({
  id: '/add-job',
  path: '/add-job',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserEditJobUuidRoute = UserEditJobUuidRouteImport.update({
  id: '/edit-job/$uuid',
  path: '/edit-job/$uuid',
  getParentRoute: () => UserRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/user/add-job': typeof UserAddJobRoute
  '/user/board': typeof UserBoardRoute
  '/user/home': typeof UserHomeRoute
  '/user/your-list': typeof UserYourListRoute
  '/user/edit-job/$uuid': typeof UserEditJobUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/user/add-job': typeof UserAddJobRoute
  '/user/board': typeof UserBoardRoute
  '/user/home': typeof UserHomeRoute
  '/user/your-list': typeof UserYourListRoute
  '/user/edit-job/$uuid': typeof UserEditJobUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/user/add-job': typeof UserAddJobRoute
  '/user/board': typeof UserBoardRoute
  '/user/home': typeof UserHomeRoute
  '/user/your-list': typeof UserYourListRoute
  '/user/edit-job/$uuid': typeof UserEditJobUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/landing'
    | '/login'
    | '/user/add-job'
    | '/user/board'
    | '/user/home'
    | '/user/your-list'
    | '/user/edit-job/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user'
    | '/landing'
    | '/login'
    | '/user/add-job'
    | '/user/board'
    | '/user/home'
    | '/user/your-list'
    | '/user/edit-job/$uuid'
  id:
    | '__root__'
    | '/'
    | '/user'
    | '/landing'
    | '/login'
    | '/user/add-job'
    | '/user/board'
    | '/user/home'
    | '/user/your-list'
    | '/user/edit-job/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRouteRoute: typeof UserRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/your-list': {
      id: '/user/your-list'
      path: '/your-list'
      fullPath: '/user/your-list'
      preLoaderRoute: typeof UserYourListRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/home': {
      id: '/user/home'
      path: '/home'
      fullPath: '/user/home'
      preLoaderRoute: typeof UserHomeRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/board': {
      id: '/user/board'
      path: '/board'
      fullPath: '/user/board'
      preLoaderRoute: typeof UserBoardRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/add-job': {
      id: '/user/add-job'
      path: '/add-job'
      fullPath: '/user/add-job'
      preLoaderRoute: typeof UserAddJobRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/edit-job/$uuid': {
      id: '/user/edit-job/$uuid'
      path: '/edit-job/$uuid'
      fullPath: '/user/edit-job/$uuid'
      preLoaderRoute: typeof UserEditJobUuidRouteImport
      parentRoute: typeof UserRouteRoute
    }
  }
}

interface UserRouteRouteChildren {
  UserAddJobRoute: typeof UserAddJobRoute
  UserBoardRoute: typeof UserBoardRoute
  UserHomeRoute: typeof UserHomeRoute
  UserYourListRoute: typeof UserYourListRoute
  UserEditJobUuidRoute: typeof UserEditJobUuidRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserAddJobRoute: UserAddJobRoute,
  UserBoardRoute: UserBoardRoute,
  UserHomeRoute: UserHomeRoute,
  UserYourListRoute: UserYourListRoute,
  UserEditJobUuidRoute: UserEditJobUuidRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRouteRoute: UserRouteRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
